name: my_terraform_pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'main'
        type: choice
        options:
          - dev
          - stage
          - prod
  
  env:
    TERRAFORM_VERSION: '1.14.6'
  
  permission:

